In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split  # helps in dividing training & testing parts
from sklearn.preprocessing import LabelEncoder        # helps in converting text columns to numbers(eg male-1, female-0)

In [3]:
df = pd.read_csv("C:/Users/user/Desktop/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head() # displays top 5 rows of data frame.

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
print(df.isnull().sum()) # helps in checking missing values in each column
print(df.dtypes)

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64
customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [7]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce') # This converts the 'TotalCharges' column to numeric data type.
                                                                    # If some values cannot be converted (like text, blank spaces, etc.)
                                                                   # they are turned into NaN (missing values) because of errors='coerce'.
df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].median()) #This fills the missing values (NaN) in 'TotalCharges' 
                                                                            #with the median value of that column.

In [8]:
df.drop(['customerID'], axis=1, inplace=True)  #Remove the customerID column from the dataset permanently.

In [9]:
cat_cols = df.select_dtypes(include='object').columns

le = LabelEncoder()            #This code converts all text columns into numbers so that machine learning models can understand them.
for col in cat_cols:
    df[col] = le.fit_transform(df[col])

In [10]:
# Splitting data into two parts training & testing(80% and 20%)
X = df.drop('Churn', axis=1)
y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

Train shape: (5634, 19)
Test shape: (1409, 19)